### ISSUE TITLE
Unclear when viz is actually ready

### ISSUE THREAD

**Issue by aezell** [stoddabr/react-tableau-embed-live#19]
Sorry to post this here but I don't have a Twitter account to contact you with.

My use case is that I want to apply a filter as soon as I can after the viz has loaded. 

I assumed I could use the `onCustomViewLoaded` callback to call a function that does something similar to your "Add a Filter" example using the `useRef` to pass a `vizRef` to `TableauEmbed`. However, when that callback fires, `vizRef.current` is `undefined`. 

Is there another callback I should be using?

My current code looks like this:
```javascript
const addUserFilter = (userId) => {
  if (vizRef && vizRef.current) {
    const viz = vizRef.current
    viz.addFilter('user_id', userId)
  }
}
```

**Comment by aezell** [comment]
It helps if I don't gate the `TableauEmbed` off in a conditional. Sorry for the noise.

**Comment by stoddabr** [comment]
No worries! I haven't checked Twitter in ages -- should probably change that. Glad you figured it out. 

Is there anything that could be added to the readme to help others who might fall into a similar issue?

**Comment by aezell** [comment]
I think the difference between `addFilter` and `applyFilterAsync` is confusing in the Tableau docs. It's not your library's fault. It talks about using `addFilter` before initialization but in the React scenario, it's a bit unclear when that would actually occur. The fact that it simply rerenders the viz if you use it afterwards is a clue about what's happening. But, it's not something that might be immediately apparent.

That said, if it would be possible to have a `VizFilter` component that I could drop inside the `TableauEmbed` block, that would be really cool. Something like this:
```javascript
<TableauEmbed url='https://tableau.com'>
  <VizFilter field='username' value={username} />
</TableauEmbed>
```
That would initialize the filters as written. Then, I could still have the more advanced `applyFilterAsync` functions for "interactive" filtering if I want them. Anything that mirrors the React components more closely to the "WebComponent" pattern in the Tableau documentation seems like it would be easier for users to make sense of. Well, at least this user. :)
