### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by kaichiangbain** [stoddabr/react-tableau-embed-live#22]
This is probably very obvious to many, but not me. 

ERROR in C:/.../node_modules/@stoddabr/react-tableau-embed-live/dist/react-tableau-embed-live.es.js 738:117
Module parse failed: Unexpected token (738:117)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| }
| function Mt(e, l) {
>   const [h, a] = xe(() => !e || l != null && l.shouldPreventLoad ? "idle" : typeof window > "u" ? "loading" : ee[e] ?? "loading"), [P, _] = xe("");
|   return dt(() => {
|     if (!e || l != null && l.shouldPreventLoad)

Also, is this MIT license? Don't see a license file.

**Comment by stoddabr** [comment]
Very strange. This is not obvious to me at all. Did you end up finding a fix?

Also, I'm still working on a license. I'm planning on adding a license in a future 1.0 release but if that's hampering adoption I would accept a PR adding one.

**Comment by ehossack** [comment]
> 
> Also, I'm still working on a license. I'm planning on adding a license in a future 1.0 release but if that's hampering adoption I would accept a PR adding one.

You can use the Github UI to choose and add an appropriate license very easily!
Unambiguously, it's best to be you, since you are the defacto code owner. :)

**Comment by stoddabr** [comment]
Added MIT license 😄 🚀
