### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by vallereaugabriel** [stoddabr/react-tableau-embed-live#30]
I cannot get to use the `TableauEmbed` component or the `useTableau` hook. Even copy pasting the basic example I get a cryptic runtime error.

```json
"react": "^17.0.2",
"typescript": "^5.1.6",
```

If I copy paste the contents of [TableauViz.tsx](https://github.com/stoddabr/react-tableau-embed-live/blob/main/src/lib/TableauEmbed/TableauViz.tsx) though, it works. And the types too.

I'll provide more details if no one can reproduce the runtime error.

I've come up with an hybrid version for now, importing all the types at the right place but it would be even better if I could use the whole thing.

I'd really like to thanks the author by the way, it's still really nice to have `tableauRef.current.refreshDataAsync()` properly typed.

**Comment by stoddabr** [comment]
Hi, At first glance, it sounds like an error caused by conflicting
dependencies. What version of react are you using?

More details couldn't hurt: what are your package.json dependencies, could
you copy/screenshot the entire error, and add any other info that could be
related?

**Comment by vallereaugabriel** [comment]
I think I might have updated packages and fixed the issue. Thank you for your answer.
```json
    "@stoddabr/react-tableau-embed-live": "^0.3.27",
    "react": "^18.2.0",
    "typescript": "^5.3.3",
```
