### ISSUE TITLE
React Testing Library dependency?

### ISSUE THREAD

**Issue by TheMoonDawg** [stoddabr/react-tableau-embed-live#32]
Hello! Is there a reason `@testing-library/react-hooks` is listed as a dependency and not a dev dependency?

We're getting peer dependency warnings in our project because we're on React DOM 18 and that version only supports v16/17. There's also no need to include a testing library in the published package.

Thanks!

**Comment by stoddabr** [comment]
Good catch. Merging this PR now: https://github.com/stoddabr/react-tableau-embed-live/pull/33

**Comment by stoddabr** [comment]
Hopefully that fixed your issue! Please let me know either way. 

I personally haven't experimented with rendering the tableau embedded api server side so I'd be interested to hear if you have any success with that

**Comment by TheMoonDawg** [comment]
Awesome, thanks for the quick turnaround!
